### ISSUE TITLE
Implement dropdown menus 

### ISSUE THREAD

**Issue by linarietuma** [kymckay/f28cd-project#12]
- [x] Basic HTML layout
- [x] CSS formatting - year 
- [x] CSS formatting - prediction data 
- [ ] JS formatting  
- [ ] Full functionality

**Comment by linarietuma** [comment]
Since changing the underlying javascript for the dropdown menus, some formatting needs to be added for both year and prediction data dropdowns.

**Comment by kymckay** [comment]
Done in #36
