### ISSUE TITLE
A voter in Edinburgh East wants to see who won their constituency in 2019 and by what margin.

### ISSUE THREAD

**Issue by kymckay** [kymckay/f28cd-project#2]
- [x] They set the year to 2019 from a dropdown. 
- [x] They either search for their postcode or click it on the map. 
- [x] The breakdown graph updates to reflect the votes cast within Edinburgh East. 
- [x] The politician profile updates to reflect the MP who won the constituency and by what margin.

**Comment by linarietuma** [comment]
- Dropdown works
- Postcode search works, no constituency search implemented.
- Cross-interactivity between map, graph and candidate's profile not yet implemented
