### ISSUE TITLE
Show constituency polygons on the map

### ISSUE THREAD

**Issue by kymckay** [kymckay/f28cd-project#56]
This might be a tricky one. I think the client will need to request the GeoJSON file from the server and then probably the Mapbox GL JS package we're using has some built in functionality to render GeoJSON as a layer.

Could also add a convenience function to the data loading script to automatically fetch and save the GeoJSON file for us instead of manually retrieving it like currently specified.

**Comment by jonleesy** [comment]
@kymckay I think I could try to work on this data loading instead, might have figured out how to add polygons on the map.

**Comment by kymckay** [comment]
@jonleesy Yeah feel free to assign yourself

I can tackle #55 then

**Comment by jonleesy** [comment]
I seem to have a problem with mongo DB here. Will try to fix it first.

`MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/Users/jonlee/Documents/GitHub/f28cd-project/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        address: 'localhost:27017',
        error: Error: connect ECONNREFUSED 127.0.0.1:27017
            at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 128672376,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! f28cd-project@0.0.1 start:server: `node server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the f28cd-project@0.0.1 start:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonlee/.npm/_logs/2021-03-18T13_53_39_130Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! f28cd-project@0.0.1 start: `npm run build && npm run start:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the f28cd-project@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonlee/.npm/_logs/2021-03-18T13_53_39_172Z-debug.log`

**Comment by jonleesy** [comment]
Hey @kymckay I'm struggling to connect to `npm start`. Did all the `npm run build:data` and was successful, but still stuck with bunch of errors.

**Comment by kymckay** [comment]
@jonleesy Do you have MongoDB running?

That's a good point actually, I should add some failsafe to gracefully handle starting without MongoDB present

**Comment by jonleesy** [comment]
Managed to resolve it. Realised that I have an older version of MongoDb installed and it was a different command on Mac – Pre and Post Catalina update – to start MongoDb. Updated to the latest and apparently the command has changed.

**Comment by jonleesy** [comment]
@kymckay Still really confused on how the DB extraction works 😅. Can I push what I've done and you take a look?

**Comment by kymckay** [comment]
@jonleesy You can, although this task doesn't involve any DB extraction 😆

**Comment by jonleesy** [comment]
Sorry, meant to say injection – loading data into the DB 🤣
