### ISSUE TITLE
Unique colours for individual constituency tiles

### ISSUE THREAD

**Issue by jonleesy** [kymckay/f28cd-project#67]
Map tiles should should unique colours of winning party for each year. Could be done by some function with parameter: `getColour(year, ['get', 'pcon19cd'])`, where `['get', 'pcon19cd']` should return constituency code.

Function to be used within `'fill-color'`
```ruby
// add polygon fill
map.addLayer({
  'id': 'polygons-fill',
  'type': 'fill',
  'source': 'polygons',
  'layout': {},
  'paint': {
    'fill-color': '#7f5a83',
    'fill-opacity': 0.3,
  }
});
``` 
of `map.js`

**Comment by jonleesy** [comment]
@kymckay was wondering if there is a function for this already.

**Comment by kymckay** [comment]
@jonleesy Afraid not, I'm going to try and handle this now as currently doing the same thing for the graph element (need to add colours into the database so they can be accessed programmatically)

**Comment by kymckay** [comment]
In fact, I'll leave this for now and get the other colouring merged in on it's own. May need to restructure the way the client is handling data (do it in a centralised module) for this one

**Comment by jonleesy** [comment]
@kymckay I just had another thought. Might need a similar function, that takes in `year` and `pcon19cd` as parameter and return a winning party name, just so that we could show it on the popup label on the map

**Comment by kymckay** [comment]
Did some more research into how this package works to enable data-driven styling.

Unfortunately it's not just as simple as making a function that takes the gss code property (there's no convenient way to get the property out into the code). What we need to do is turn the list of gss codes into a [paint fill specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-fill-fill-color) using a [match expression](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#match) then apply that to the map.
