### ISSUE TITLE
Search for Constituency on Map

### ISSUE THREAD

**Issue by jonleesy** [kymckay/f28cd-project#77]
- [ ] to inject constituency names with bounds into map. Would most likely be a map feature layer

**Comment by jonleesy** [comment]
@kymckay  currently working on this. But each time when running `npm start`, console throws error: `(node:7345) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency`.

**Comment by kymckay** [comment]
@jonleesy Unfortunately I can't reproduce it which makes me think it's setup specific, try running `npm install` again maybe?

**Comment by jonleesy** [comment]
Its currently returning results:
![image](https://user-images.githubusercontent.com/65177718/112005815-0178bd80-8b1b-11eb-8f24-9f64c362945e.png)

but upon clicking, it returns the geometry of the polygon instead: 

![image](https://user-images.githubusercontent.com/65177718/112006429-9976a700-8b1b-11eb-9fc4-7aef1939fe2f.png)

**Comment by jonleesy** [comment]
My suggestion is to remove specific pins on searches and just focus on constituency search. 
Searching for a place in specific will bring you to the constituency anyways, just would not be marked. 

After all, the focus would be on constituency votes. 

@kymckay @LinaRietuma @ig019

**Comment by jonleesy** [comment]
Will PR and review from there.
