### ISSUE TITLE
Update all other sections when clicking a constituency

### ISSUE THREAD

**Issue by kymckay** [kymckay/f28cd-project#85]
Need to filter data to constituency and then should just be a case of using existing methods.

The list filtering will require some new code, but could perhaps factor out some common behaviour with the search which is effectively a filter

**Comment by kymckay** [comment]
@jonleesy As you've explored more of Mapbox GL JS package than me, are you aware of any way to register event handlers for when the user clicks a constituency in the GeoJSON layer?

**Comment by jonleesy** [comment]
yes. can use something like:

`map.on('mouse click', 'constituency-fill', function(e) {};` with `constituency-fill` being the layer of polygons.
